### ISSUE TITLE
Translate to English or Indonesian

### ISSUE THREAD

**Issue by agungjk** [iview/iview-doc#12]
can i contribute to this project with translating doc to english or indonesian?

**Comment by icarusion** [comment]
欢迎，你的中文怎么样呢？

**Comment by agungjk** [comment]
I'm sorry, my chinese is bad.
I can use google translate or request my friend to translate it.

对不起，我的中文不好
我可以使用谷歌翻译或请求我的朋友翻译它。

**Comment by hanzoz** [comment]
the content are mostly in chinese and some of the links actually doesn't link to english documentation although it there was a link and redirect to main page, maybe you can help open up to us so that some of us can contribute to it.

我也和agungjk一样，我还能看少许中文，只是觉得如果没英文文档，对我们会有一点麻烦。

**Comment by lcx960324** [comment]
The translation is working in progress.
We're glad if you can help us translate some parts.
You can contribute your translation by simply committing a pull request.

Those links redirected to main page are pages that is not translated.

Thx for ur advise and we'll consider about it.

**Comment by icarusion** [comment]
All translations have been completed now.
