### ISSUE TITLE
A typo in Internationalization page on English

### ISSUE THREAD

**Issue by gamtiq** [iview/iview-doc#15]
There is the following typo in [i18n-en.vue](https://github.com/iview/iview-doc/blob/master/src/views/guide/i18n-en.vue#L11):
> We need the help of *bebel* to import iView language packages:

**Comment by lcx960324** [comment]
Thank you for your feedback. But I didn't find any typo there. Could you please provide a more detailed description? Thx a lot.

**Comment by gamtiq** [comment]
Should be Babel (or babel) instead of *bebel*.

**Comment by lcx960324** [comment]
Oh! Got it! Thanks a lot.
