### ISSUE TITLE
Please optimize the performance of the web site

### ISSUE THREAD

**Issue by Kinghts** [iview/iview-doc#38]
### page：
https://www.iviewui.com/docs/guide/introduce
### cpu usage：
![default](https://user-images.githubusercontent.com/7201507/36641165-1e3adc7e-1a66-11e8-98bd-dd725a10ad22.PNG)
### machine cpu：
i7-8550u

**Comment by lcx960324** [comment]
跑了一下 performance 没有发现性能问题，Windows 的任务管理器不能作为性能指标的参考依据吧，看一下是不是你的 firefox 有问题。
