### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by azamat-sharapov** [iview/iview-doc#46]
https://www.iviewui.com/ shows blank page. Looks like file.iviewui.com is down.

**Comment by azamat-sharapov** [comment]
![image](https://user-images.githubusercontent.com/3023661/40060476-26a72b40-5870-11e8-8020-127ea8ca02bb.png)

**Comment by icarusion** [comment]
@azamat-sharapov What country are you from?

**Comment by azamat-sharapov** [comment]
@icarusion from Uzbekistan. Also check out similar issues:  
https://github.com/iview/iview/issues/3580  
https://github.com/iview/iview/issues/3602

**Comment by icarusion** [comment]
file.iviewui.com domain use CDN, Before the service provider hung for a few minutes, but it should be possible now. Could you open https://www.iviewui.com/ in privacy window of Chrome, if not work , please screenshot a image in devtool of `network`

**Comment by azamat-sharapov** [comment]
![image](https://user-images.githubusercontent.com/3023661/40159635-a88b9584-59c3-11e8-964b-832ce71248f4.png)

**Comment by icarusion** [comment]
Wait a minute, I just contacted the CDN provider and let them change my domain to global coverage.You should be able to access it later, and we will also deploy a set of documentation on GitHub in the future.

**Comment by azamat-sharapov** [comment]
Finally works. Thanks!

**Comment by cuzox** [comment]
And now the website is down again.
How are we supposed to use the library if we can't access the docs?
Also, how can we report an issue about the website being down if we can only submit the issues through the website?

C'mon @icarusion, what is this.

ISSUE #4812
I get blank page. The console error is:
GET https://icarusion.gitee.io/iview/main.7ac238fe67d3245c4e37.js
net::ERR_NAME_RESOLUTION_FAILED

I'm in Dominican Republic

**Comment by cuzox** [comment]
It's working again!
