### ISSUE TITLE
Some links are not working

### ISSUE THREAD

**Issue by BigChief45** [iview/iview-doc#8]
Some links in the documentation do not work. For example, when clicking on the _Grid_ component link, it redirects back to the home page. Same as when you click on the _Practice_ link.

**Comment by icarusion** [comment]
Sorry about that. We are translating doc to English, so somepage will redirect to home.

**Comment by icarusion** [comment]
Click Button `中文` can view all pages

**Comment by BigChief45** [comment]
Thanks for the quick response. Are translation contributions welcomed? I think my Chinese is good enough for translating some of the [missing components](https://github.com/iview/iview-doc/projects/1). I would love to contribute to this project.
